<a href="https://colab.research.google.com/github/NeonKazuha/Text-Summarizer/blob/main/ExtractiveTextSummarizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

File ‘bbc_text_cls.csv’ already there; not retrieving.



In [2]:
import pandas as pd
import nltk
import re
import numpy as np

In [3]:
df = pd.read_csv('bbc_text_cls.csv')
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [4]:
df['text'][0]

'Ad sales boost Time Warner profit\n\nQuarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.\n\nThe firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.\n\nTime Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL\'s underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers and will try to sig

In [5]:
input = df['text'][0].splitlines()
input

['Ad sales boost Time Warner profit',
 '',
 'Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.',
 '',
 'The firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.',
 '',
 "Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers a

In [6]:
# Sentence Tokenization
text_in = []
for i, sent in enumerate(input):
  if i % 2 == 0:
    text_in.append(sent)

text_in

['Ad sales boost Time Warner profit',
 'Quarterly profits at US media giant TimeWarner jumped 76% to $1.13bn (£600m) for the three months to December, from $639m year-earlier.',
 'The firm, which is now one of the biggest investors in Google, benefited from sales of high-speed internet connections and higher advert sales. TimeWarner said fourth quarter sales rose 2% to $11.1bn from $10.9bn. Its profits were buoyed by one-off gains which offset a profit dip at Warner Bros, and less users for AOL.',
 "Time Warner said on Friday that it now owns 8% of search-engine Google. But its own internet business, AOL, had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits were lower than in the preceding three quarters. However, the company said AOL's underlying profit before exceptional items rose 8% on the back of stronger internet advertising revenues. It hopes to increase subscribers by offering the online service free to TimeWarner internet customers and will try to 

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
len(text_in)

6

In [9]:
len(max(text_in))

607

In [10]:
len(min(text_in))

33

In [11]:
tfidf = TfidfVectorizer(stop_words='english')

In [12]:
vec = tfidf.fit_transform(text_in)
vec

<6x178 sparse matrix of type '<class 'numpy.float64'>'
	with 219 stored elements in Compressed Sparse Row format>

In [22]:
vec[0].nnz

6

In [21]:
sums = np.sum(vec, axis = 1)
sums

matrix([[2.39300325],
        [3.68560022],
        [5.24549179],
        [7.23194779],
        [7.73642734],
        [6.22291131]])

In [28]:
tfidf_mean = [(sums[i]/(vec[i].nnz)) for i in range(len(sums))]
tfidf_mean.index(max(tfidf_mean))

0

In [30]:
tfidf_mean

[matrix([[0.39883388]]),
 matrix([[0.26325716]]),
 matrix([[0.16920941]]),
 matrix([[0.12468876]]),
 matrix([[0.11902196]]),
 matrix([[0.13828692]])]

In [31]:
text_in[tfidf_mean.index(max(tfidf_mean))]

'Ad sales boost Time Warner profit'

## Combining Everything

In [45]:
def extractive_sumarry(text):
  input = text.splitlines()
  text_in = []
  for i, sent in enumerate(input):
    if i % 2 == 0: # This dataset is somehow flawed that's why, remove for other datasets
      text_in.append(sent)

  # print(text_in)

  vec = tfidf.fit_transform(text_in)
  sums = np.sum(vec, axis = 1)
  tfidf_mean = [(sums[i]/(vec[i].nnz)) for i in range(len(sums))]
  tfidf_mean.index(max(tfidf_mean))
  return text_in[tfidf_mean.index(max(tfidf_mean))]

In [48]:
extractive_sumarry(df['text'][10])

'Ask Jeeves tips online ad revival'